---
title: "Solution -- Mean, variance & standard deviation"
author: "Carlo Knotz"
date: "9/14/2021"
output: pdf_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```

## Introduction

Below are the correct solutions (means, variance and standard deviation scores) to the four exercises I posted on Canvas a few days ago.

Be aware: These solutions were calculated by a computer. Yours might be slightly different due to rounding, which is not a problem. See also the example calculation in Excel using the income example (Exercise 4).

  
### Exercise 1: Body height

The set of body height measurements in cm was: `(167,189,210,154,178,186,161)`

* **Mean:** The average body height is: `r round(mean(c(167,189,210,154,178,186,161)), digits=2)`
* **Variance:** The variance (the average squared difference from the mean) is `r round(var(c(167,189,210,154,178,186,161)), digits=2)`
* **Standard deviation:** The standard deviation (the average difference from the mean) is `r round(sd(c(167,189,210,154,178,186,161)), digits=2)`

*Interpretation:* The variance gives us a general idea of the spread of our data, but "squared differences" (or, here, "squared centimeters") are obviously difficult to interpret. The standard deviation provides a more intuitive measure because it has the same unit of measurement as our original data: E.g., the average difference of our observations from their mean is: `r round(sd(c(167,189,210,154,178,186,161)), digits=2)` *centimeters*.

### Exercise 2: Left-right self-placement

The set of ideological self-placements, where 0 means "extreme left", 10 means "extreme right" and 5 means "centrist", were: `(2,5,9,4,5,4,3,7,1,10)`

* **Mean:** The average ideological position is: `r format(round(mean(c(2,5,9,4,5,4,3,7,1,10)), digits=2), nsmall=2)`
* **Variance:** The variance (the average squared difference from the mean) is `r round(var(c(2,5,9,4,5,4,3,7,1,10)), digits=2)`
* **Standard deviation:** The standard deviation (the average difference from the mean) is `r round(sd(c(2,5,9,4,5,4,3,7,1,10)), digits=2)`

The interpretation is as shown above (solution to Exercise 1), but with a different unit of measurement (here: the 0-10 self-placement scale).

### Exercise 3: Unemployment rates

The unemployment rate data (percent unemployed) for a set of countries were: `(3.4,12.5,25.2,8.9,6.4,5.1)`

* **Mean:** The average unemployment rate is: `r round(mean(c(3.4,12.5,25.2,8.9,6.4,5.1)), digits=2)`
* **Variance:** The variance (the average squared difference from the mean) is `r round(var(c(3.4,12.5,25.2,8.9,6.4,5.1)), digits=2)`
* **Standard deviation:** The standard deviation (the average difference from the mean) is `r round(sd(c(3.4,12.5,25.2,8.9,6.4,5.1)), digits=2)`

The interpretation is as shown above (solution to Exercise 1), but with a different unit of measurement (here: percent).

### Exercise 4: Income

Finally, the monthly income (in US Dollars) data of a group of people were: `(4987,3691,1634,956,8721,2782)`

* **Mean:** The average monthly income is: `r round(mean(c(4987,3691,1634,956,8721,2782)), digits=2)`
* **Variance:** The variance (the average squared difference from the mean) is `r format(round(var(c(4987,3691,1634,956,8721,2782)), digits=2),nsmall = 2)`
* **Standard deviation:** The standard deviation (the average difference from the mean) is `r round(sd(c(4987,3691,1634,956,8721,2782)), digits=2)`

The interpretation is as shown above (solution to Exercise 1), but with a different unit of measurement (here: US Dollars).
